### PR TITLE
Don't run on_killedplayer callbacks if punched player is already dead

### PR DESCRIPTION
**Pull request by ClobberXD**
If a player hits a player who's already dead, it obviously shouldn't be considered as a kill. But this does happen, and this PR fixes that. Tested.

### CODE REVIEW

**Comment by BrianGaucher** [comment]
checked the code, well coded.
Why isn't this getting merged?

**Comment by ClobberXD** [comment]
Because it hasn't been approved yet :)

**Comment by BrianGaucher** [comment]
Can I approve it? xD

**Comment by ClobberXD** [comment]
Most certainly!

(That's not enough to get it merged though... :P)

**Comment by ClobberXD** [comment]
I feel this bug is universal and should be fixed upstream. See https://github.com/minetest/minetest/pull/8462.

**Pull request merged**
